flask_starter/flaskstarter/models.py
from . import db
import datetime
from passlib.apps import custom_app_context as pwd_context


class User(db.Model):
    """User model."""

    __tablename__ = "user"
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), index=True)
    password_hash = db.Column(db.String(128))
    email = db.Column(db.String(50), unique=True, index=True)
    registered_on = db.Column(db.DateTime, default=datetime.datetime.utcnow())
    confirmed = db.Column(db.Boolean, nullable=False, default=False)

    def hash_password(self, password):
        """Model method."""
        self.password_hash = pwd_context.encrypt(password)

    def verify_password(self, password):
        """Model method."""
        return pwd_context.verify(password, self.password_hash)

    def is_authenticated(self):
        """Model method."""
        return True

    def is_active(self):
        """Model method."""
        return True

    def is_anonymous(self):
        """Model method."""
        return False

    def get_id(self):
        """Model method."""
        return unicode(self.id)
        

class Probot(db.Model):
	"""Probot model."""
	
	__tablename__ = "probot"	
	id = db.Column(db.Integer, primary_key=True)
	botname = db.Column(db.String(20), unique=True, index=True)
	is_available = db.Column(db.Boolean, nullable=False, default=True)
	battery = db.Column(db.Integer)
	registered_on = db.Column(db.DateTime, default=datetime.datetime.utcnow())
		
		

flask_starter/flaskstarter/forms/__init__.py
from ..forms.forms import *

flask_starter/flaskstarter/forms/forms.py
"""Forms.py."""
from wtforms import Form, PasswordField, TextField, RadioField, validators


class RegistrationForm(Form):
    """Registration form."""

    username = TextField(
        (u'What do you want us to call you?'),
        [validators.Length(min=3, max=15), validators.Required()]
    )
    email = TextField(
        (u'Email Address'), [validators.Length(min=6, max=35)]
    )
    password = PasswordField((u'Password'), [
        validators.Required(),
        validators.EqualTo(
            u'confirm', message=(u'Passwords must match')
        ),
        validators.Length(min=6, max=16)
    ])
    confirm = PasswordField((u'Repeat Password'))


class LoginForm(Form):
    """Login Form."""

    email = TextField(
        (u'Email Address'), [validators.Length(min=6, max=35)]
    )
    password = PasswordField((u'Password'), [
        validators.Required(),
    ])


class ResetPasswordForm(Form):
    """Reset Password Form."""

    email = TextField(
        (u'Email Address'), [validators.Length(min=6, max=35)]
    )


class ConfirmResetPasswordForm(Form):
    """Reset Password Form."""

    password = PasswordField((u'Password'), [
        validators.Required(),
        validators.EqualTo(
            u'confirm', message=(u'Passwords must match')
        ),
        validators.Length(min=6, max=16)
    ])
    confirm = PasswordField((u'Repeat Password'))
    
    
class SelectProBotForm(Form):
	
	probot = RadioField(u'Chose one:', validators = [validators.Required()], choices=[], coerce=int)
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	

flask_starter/flaskstarter/__init__.py
import os
from flask import Flask
from flask.ext.sqlalchemy import SQLAlchemy
from flask_mail import Mail
from flask.ext.babel import Babel
from flask.json import JSONEncoder

def import_modules():
    from . import views
    from . import models
    from . import logs

class CustomJSONEncoder(JSONEncoder):
    """
    This class adds support for lazy translation texts to Flask's JSON encoder.
    This is necessary when flashing translated texts.
    """

    def default(self, obj):
        from speaklater import is_lazy_string
        if is_lazy_string(obj):
            try:
                return unicode(obj)  # python 2
            except NameError:
                return str(obj)  # python 3
        return super(CustomJSONEncoder, self).default(obj)

############
# APP INIT #
############
app = Flask(__name__)
#  load settings from Config class,
#  depending on environmental variable
app.config.from_object(os.environ['APP_SETTINGS'])
app.json_encoder = CustomJSONEncoder
db = SQLAlchemy(app)
mail = Mail(app)
babel = Babel(app)

# import into module namespace
import_modules()

flask_starter/flaskstarter/logs/__init__.py
from logger import logger, syslog, loglevel

flask_starter/flaskstarter/views/__init__.py
from .. import app
from ..views.auth import auth
from ..views.main import main

app.register_blueprint(auth)
app.register_blueprint(main)

flask_starter/flaskstarter/views/auth.py
"""Authentication views blueprint."""
import datetime
from flask import Blueprint, flash, g, redirect, render_template, request, \
    url_for
from flask.ext.login import LoginManager, current_user, login_required,  \
    login_user, logout_user

# namespace .uefa
from .. import app, db
from ..decorators import check_confirmed
from ..email import send_email
from ..logs import logger
from ..models import User
from ..token import confirm_token, generate_confirmation_token
from ..forms import LoginForm, RegistrationForm, ResetPasswordForm,\
    ConfirmResetPasswordForm


auth = Blueprint('auth', __name__)


###############
# LOGIN UTILS #
###############
login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'auth.login'


@login_manager.user_loader
def load_user(id):
    return User.query.get(int(id))


@app.before_request
def before_request():
    g.user = current_user


##############
#  Register  #
##############
def send_confirm_email(user_email=None, username=None, confirm_url=None):
    """Send confirm email address."""
    if app.config['TESTING']:
        msg = 'Email not sent. You are in TESTING mode!'
        print(msg)
        logger.info(msg)
        return True
    root_url = app.config.get('ROOT_URL')
    with app.app_context():
        html = render_template(
            'user/activate.html',
            confirm_url=confirm_url,
            username=username,
            root_url=root_url
        )
        subject = 'Please confirm your email'
        try:
            send_email(user_email, subject, html)
            logger.info(
                'confirmation email sent to {}'.format(user_email)
            )
            return True
        except Exception as e:
            logger.error(
                'confirmation email could not be sent. User {0}. Error {1}'
                .format(user_email, e)
            )
            return False


@auth.route('/register', methods=['GET', 'POST'])
def register():
    """Register user."""
    form = RegistrationForm(request.form, country='CL')
    if request.method == 'POST' and form.validate():
        email_exists = User.query.filter_by(email=form.email.data).first()
        if email_exists:
            flash(u'Email address already exists', 'warning')
        else:
            user = User(
                username=form.username.data,
                email=form.email.data,
            )
            user.hash_password(form.password.data)
        try:
            db.session.add(user)
            db.session.commit()
            #  generate token and send email
            token = generate_confirmation_token(user.email)
            confirm_url = url_for(
                'auth.confirm_email',
                token=token,
                _external=True
            )
            send_confirm_email(
                user_email=user.email,
                confirm_url=confirm_url,
                username=user.username
            )
            logger.info(
                'new user registered. {}'.format(user)
            )
            flash(
                'Thanks for registering with us. \
                A confirmation email has been sent via email.', 'success'
            )
        except Exception as e:
            # TODO deal with duplicate email addresses
            db.session.rollback()
            logger.error(
                'new user could not be registered. {0}'.format(e)
            )
        finally:
            db.session.close()
        return redirect(url_for('auth.login'))
    return render_template(
        'register.html',
        form=form,
    )


@auth.route('/unconfirmed')
def unconfirmed():
    """Return unconfirmed template."""
    if hasattr(current_user, 'confirmed') and current_user.confirmed:
        return redirect(url_for('auth.login'))
    flash('Please confirm your account!', 'warning')
    return render_template('unconfirmed.html')


@auth.route('/confirm/<token>')
def confirm_email(token):
    """Confirm token with email address using token."""
    user = None
    email = confirm_token(token)
    if email:
        try:
            user = User.query.filter_by(email=email).first()
        except Exception as e:
            flash(
                'Sorry, we could not find your account in our database.', 'warning'
            )
            logger.error('error {}. email {}'.format(e, email))
        if not user:
            logger.error(
                'user could not be confirmed. email {}'.format(email)
            )
            flash('We could not verify your email address.', 'warning')
            return redirect(url_for('auth.register'))
        if user.confirmed:
            flash('Account already confirmed. Please login.', 'success')
        else:
            user.confirmed = True
            user.confirmed_on = datetime.datetime.now()
            try:
                db.session.add(user)
                db.session.commit()
                logger.info(
                    'user confirmed. {}'.format(user)
                )
            except Exception as e:
                db.session.rollback()
                logger.error(
                    'user could not be confirmed. {0}. {1}'.format(user, e)
                )
                raise
            finally:
                db.session.close()
            flash('You have confirmed your account. Thanks!', 'success')
    else:
        flash('The confirmation link is invalid or has expired.', 'warning')
    return redirect(url_for('auth.login'))


@auth.route('/reset_password', methods=['GET', 'POST'])
@check_confirmed
def reset_password():
    """Request password reset."""
    form = ResetPasswordForm(request.form)
    if request.method == 'POST' and form.validate():
        #  check user email exists
        email = request.form['email'].strip()
        user = User.query.filter_by(email=email).first()
        if user:
            token = generate_confirmation_token(user.email)
            confirm_url = url_for(
                'auth.confirm_reset_password',
                token=token,
                _external=True
            )
            html = render_template(
                'user/password_reset_email.html',
                confirm_url=confirm_url,
                username=user.username
            )
            subject = "Password Reset Request"
            send_email(email, subject, html)
            msg = 'Password reset request email sent to {}'.format(user.email)
            logger.info(msg)
            flash(msg, 'success')
            return redirect(url_for('auth.login'))
        #  flash('Email address not found for any user', 'warning')
        flash(
            'Email address not found for any user',
            'warning'
        )
    return render_template(
        'reset_password_request.html',
        form=form
    )


@auth.route('/confirm_reset_password/<token>', methods=['GET', 'POST'])
@check_confirmed
def confirm_reset_password(token):
    """Confirm password reset."""
    form = ConfirmResetPasswordForm()
    if request.method == 'POST' and form.validate():
        try:
            email = confirm_token(token)
        except Exception as e:
            flash(
                'The confirmation link is invalid or has expired.',
                'warning'
            )
        user = User.query.filter_by(email=email).first_or_404()
        if not user.confirmed:
            flash(
                'You must confirm your account first',
                'warning'
            )
        else:
            pwd = request.form['password'].strip()
            user.hash_password(pwd)
            try:
                db.session.add(user)
                db.session.commit()
                logger.info(
                    'Password reset. {}'.format(user)
                )
            except Exception as e:
                db.session.rollback()
                error_msg = 'Your password could not be changed at this time. \
                    {}'.format(user)
                logger.error('{0} {1}'.format(error_msg, e))
                flash(error_msg, 'warning')
                raise
            finally:
                db.session.close()
            flash('You have successfully changed your password.', 'success')
            return redirect(url_for('auth.login'))
    return render_template(
        'reset_password_confirm.html',
        token=token,
        form=form
    )


@auth.route('/login', methods=['GET', 'POST'])
def login():
    """User login."""
    form = LoginForm(request.form)
    # is user authenticated go straight to default template
    if g.user.is_authenticated:
        return redirect(url_for('index'), code=302)
    if request.method == 'POST' and form.validate():
        email = request.form['email']
        password = request.form['password']
        registered_user = User.query.filter_by(
            email=email
        ).first()
        if registered_user is None or not registered_user.verify_password(password):
            msg = 'Email or Password is invalid'
            logger.info(
                '{0} email: {1}'.format(msg, email)
            )
            flash(msg, 'warning')
            return redirect(url_for('auth.login'))
        if not registered_user.confirmed:
            logger.info(
                'unconfirmed user login attempt. email: {0}'.format(email)
            )
            return redirect(url_for('auth.unconfirmed'))
        login_user(registered_user)
        logger.info(
            'user login.  user: {0}'.format(current_user)
        )
        return redirect(url_for('index'), code=302)
    return render_template(
        'login.html',
        form=form
    )


@auth.route('/logout')
@login_required
def logout():
    """User logout."""
    logger.info(
        'user logout. user: {0}'.format(current_user)
    )
    logout_user()
    return redirect(url_for('auth.login'))

flask_starter/flaskstarter/views/main.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .. import app, db
from ..models import Probot
from ..forms import SelectProBotForm
from flask.ext.login import login_required
import json

main = Blueprint('main', __name__)



@app.route('/', methods=['GET', 'POST'])
def index():
	"""Index."""
	return render_template('index.html')
    
@app.route('/probots', methods=['GET', 'POST'])
@login_required
def probots():
		
	available_probot = True		#variable to control the HTML content, True: Shows the form 
								#False: Shows a message saying there aren't probots available
	
	form = SelectProBotForm(request.form)

	probots_available_q = Probot.query.filter_by(is_available=1).order_by('botname').all() #queries the database for available probots 
																						   #Returns a list	
	if probots_available_q == []:	#NO probots available
	
		available_probot = False
		
	else:							#At least one probot available

		form.probot.choices = [(probot.id, probot.botname+" "+"["+ str(probot.battery) +"%]") 
			for probot in probots_available_q]	#Fills the form with a radio button for each available probot

		if request.method == 'POST' and form.validate() == False:	#NO radio button checked
	
			form.probot.errors = ['You need to select one ProBot to continue']	#Shows an error in the form
		
		elif request.method == 'POST' and form.validate():			#ALL went good
		
			chosen_probot_id = form.probot.data		#Get chosen probot id from the form
			chosen_probot = Probot.query.filter_by(id = chosen_probot_id).first()			
			chosen_probot.is_available = False
			
			try:
				db.session.add(chosen_probot)
				db.session.commit()               
			except:			
				db.session.rollback()
				error_msg = 'Could not change the ProBot\'s availability'
				flash(error_msg, 'warning')
				raise
			finally:
				db.session.close()
			
			if request.user_agent.platform == ('android' or 'iphone' or 'ipad'):
				return render_template('botcontrolphone.html', chosen_probot_id=chosen_probot_id)				
			else:
				return render_template('botcontrol.html', chosen_probot_id=chosen_probot_id) #render the file with the probot control "console"

	return render_template('probots.html', form=form, available_probot=available_probot)

@app.route('/bridge', methods=['POST'])
def message():
    probot_id = None
    body = json.loads(request.get_data())
    print("args:", body["args"], "kwargs:", body["kwargs"])
    print(body["args"][0])  
    probot_id = int(body["args"][0])
    probot = Probot.query.filter_by(id = probot_id).first()			
    probot.is_available = True
    
    try:
        db.session.add(probot)
        db.session.commit()
        print("ProBot {} availability set to True".format(probot_id))
        probot_id = None               
    except:			
        db.session.rollback()
        print("Could not change ProBot {} availability".format(probot_id))
        probot_id = None
        raise
    finally:
        db.session.close()
        
    return b"OK"

flask_starter/flaskstarter/templates/_formhelpers.html
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

flask_starter/flaskstarter/templates/base.html
<!doctype html>
<html class="no-js" lang="">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    {% block title %}
    <title>Probot Project</title>
    {% endblock %}
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <!-- Place favicon.ico in the root directory -->

   <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='css/style.css' )}}">

  </head>
  <body>
    <!--[if lt IE 8]>
      <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <!-- navigation -->
    <nav>
      <a href="{{ url_for('index') }}">Home</a>
      {% if g.user.is_authenticated %}
      <a href="{{ url_for('probots') }}">ProBots</a>
      <a href="{{ url_for('auth.logout') }}">Logout</a>
      <a href="{{ url_for('auth.reset_password') }}">Change Password</a>
      {% else %}
      <a href="{{ url_for('auth.register') }}">Register</a>
      <a href="{{ url_for('auth.login') }}">Login</a>
      {% endif %}
    </nav>
    <!-- / navigation -->
    
    <!-- messages -->
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div>
      {% for category, message in messages %}
        <div class="message-card {{ category }}">{{ message }}</div>
      {% endfor %}
    </div>
    {% endif %}
    {% endwith %}
    <!-- / messages -->
    
    <!-- main content -->
    <main>
    {% block content %}
    {% endblock %}
    </main>
    <!-- / main content -->

    <!-- Google Analytics: change UA-XXXXX-Y to be your site's ID. -->
    <script>
        window.ga=function(){ga.q.push(arguments)};ga.q=[];ga.l=+new Date;
        ga('create','UA-XXXXX-Y','auto');ga('send','pageview')
    </script>
    <script src="https://www.google-analytics.com/analytics.js" async defer></script>
  </body>
</html>

flask_starter/flaskstarter/templates/botcontrol.html
<!DOCTYPE html>
<html lang='en'>
<head>
	<link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='css/style_video_template.css' )}}">
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
	<script>AUTOBAHN_DEBUG = true;</script>
	<script src="http://autobahn.s3.amazonaws.com/autobahnjs/latest/autobahn.min.jgz"></script>
	<script type="text/javascript" probot_id="{{ chosen_probot_id }}" src="{{ url_for('static', filename='js/keyjoy.js' )}}"></script>

</head>
<body>
	<div style=" top: 10%; margin-left: 10%; width:80%; height:600px" id = 'main' class='main' >
		<iframe src="https://videolink2.me/probot{{ chosen_probot_id }}" frameborder="0" scrolling="yes"></iframe>    
	</div>

	<div style="top:70%;text-align: center; position:relative; width: 100%; border-width: 1px 0 0 0; ">
	
		<h3><p>Choose the device that you want to control the ProBot. To change your choice, refresh the Webpage.</p></h3>
		<button id="keyboard" onclick="chooseControl(this.id)">Keyboard</button>
		<button id="joystick" onclick="chooseControl(this.id)">Joystick</button>
		
	</div>
	<div style="top:75%;text-align: center; position:relative; width: 100%; border-width: 1px 0 0 0; ">
		<input type="text" id="battery" />
	</div>

</body> 	
</html>

flask_starter/flaskstarter/templates/botcontrolphone.html
<!DOCTYPE html>
<html lang='en'>
<head>
	<link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='css/style_video_template.css' )}}">

	<link rel="stylesheet" href="http://yoannmoinet.github.io/nipplejs/stylesheets/styles.css" media="screen" title="no title" charset="utf-8">
	<link rel="stylesheet" href="http://yoannmoinet.github.io/nipplejs/stylesheets/github-light.css" media="screen" title="no title" charset="utf-8">
	<script src="jquery-1.11.2.js"></script>
	<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
	<script>AUTOBAHN_DEBUG = true;</script>
	<script src="http://autobahn.s3.amazonaws.com/autobahnjs/latest/autobahn.min.jgz"></script>
	<script type="text/javascript" probot_id="{{ chosen_probot_id }}" src="{{ url_for('static', filename='js/nipplejs.js' )}}"></script>
</head>

<body>

	<div style=" top: 10%; margin-left: 10%; width:80%; height:600px" id = 'main' class='main' >
    	<iframe src="https://videolink2.me/probot{{ chosen_probot_id }}" frameborder="0" scrolling="yes"></iframe>    
	</div>

	<div style=" top: 60%; margin-left: 5%; width:20%; height:20%" id = 'main' class='main'>
    		<div id="left"></div>    
	</div>


	<div style=" top: 60%; margin-left: 73.5%; width:20%; height:20%" id = 'main' class='main'>
    		<div id="right"></div>  
	</div>

	<div style="top:75%;text-align: center; position:relative; width: 100%; border-width: 1px 0 0 0; ">
		<input type="text" id="battery" />
	</div>
	
	<script>

	var joystickL = nipplejs.create({
    		zone: document.getElementById('left'),
    		mode: 'static',
    		position: { left: '50%', top: '84%' },
    		color: 'green',
    		size: 150
	});


	var joystickR = nipplejs.create({
    		zone: document.getElementById('right'),
    		mode: 'static',
    		position: { left: '50%', top: '84%' },
    		color: 'red',
    		size: 150
	});
       
	</script>
</body>
</html>

flask_starter/flaskstarter/templates/index.html
{% extends 'base.html' %}

{% block content %}
  <p><b>Self balancing robot with Beaglebone Black</b></p>
  <p>
  Most robotics technologies are first implemented in military applications, most of the rest for business. Following on a history of related work, Probots are inexpensive, human-sized protest robots. No one has lost money by replacing human labor with machines, efficient devils, so the unemployment has been rising, and newly graduated Spanish students that are out of work stay too much time drinking calimocho and protesting. The indignados are unorganized and inneficient! So it is time to automate them, send robots for protests, unemploying them twice.
  </p>
  <p>
  Any protester can control the robot while sitting in the caffee or at their gardens anywhere in the work by simply using a web page to control it, but also watch, hear and speak through it.
  </p>
  <p>
  That’s why we created a self-balancing robot, with a rigid sturdy frame, with a megaphone on the top as a symbol of protest and also as a way to talk to people.
  </p>
  <p>
  This robot is 1,60m (5’/3’’) tall that self-balances in 2 wheels, driven by two EMG49 DC motors direct drive, and controlled by a Sabertooth 2X25A or Cytron 13A, 5-25V Motor Controller. The brain of the operation is a beaglebone black with an MPU6050 accelerometer and gyroscope and also optical encoders on each motor.
  </p>
  <p>
A shield was created to organize the components. In our first version, we used two batteries, one of 12V to power the control electronics and then a 24V LiPo for the motors, the second version is going to use only the 24V battery.
  </p>
  <p>
  The megaphone is a DH-12, that has a siren and a microphone, that we hacked and placed a wire to connect to a sound jack output, enabling us to connect the megaphone to almost any device (ex: cellphone, MP3 player, laptop, you name it).
  </p>
  <p>
  The system can be controlled remotely through wifi, using a cellphone hotspot connected to 3G or 4G network. It was also created an interface where you can control the robot over web page or a gamepad or even a keyboard.
  </p>
  
  
{% endblock %}

flask_starter/flaskstarter/templates/login.html
{% extends "base.html" %}

{% block content %}
{% from "_formhelpers.html" import render_field %}

<form method=post action="{{ url_for('auth.login') }}">
  <dl>
    {{ render_field(form.email) }}
    {{ render_field(form.password) }}
  </dl>
  <p><input type=submit value=Login>
</form>

<a href="{{ url_for('auth.reset_password') }}">Forgot Password?</a>

{% endblock %}

flask_starter/flaskstarter/templates/probots.html
{% extends "base.html" %}
{% block content %}


	
{% if available_probot == False %}	
	<p>Sorry, there are no ProBots available.</p>
{% else %}
	
	{% from "_formhelpers.html" import render_field %}

	<form method=post action="{{ url_for('probots') }}">

		{{ render_field(form.probot) }}

	<p><input type=submit value=Select>
	</form>
{% endif %}
	


{% endblock %}

flask_starter/flaskstarter/templates/register.html
{% extends "base.html" %}
{% block content %}
{% from "_formhelpers.html" import render_field %}

<form method=post action="{{ url_for('auth.register') }}">
  <dl>
    {{ render_field(form.username) }}
    {{ render_field(form.email) }}
    {{ render_field(form.password) }}
    {{ render_field(form.confirm) }}
  </dl>
  <p><input type=submit value=Register>
</form>

{% endblock %}

flask_starter/flaskstarter/templates/reset_password_confirm.html
{% extends "base.html" %}

{% from "_formhelpers.html" import render_field %}
{% block content %}

<form method=post action="{{ url_for('auth.confirm_reset_password', token=token) }}">
  <dl>
    {{ render_field(form.password) }}
    {{ render_field(form.confirm) }}
  </dl>
  <p><input type=submit value=Submit>
</form>
{% endblock %}

flask_starter/flaskstarter/templates/reset_password_request.html
{% extends "base.html" %}

{% block content %}
{% from "_formhelpers.html" import render_field %}

<form method=post action="{{ url_for('auth.reset_password') }}">
  <dl>
    {{ render_field(form.email) }}
  </dl>
  <p><input type=submit value=Submit>
</form>
{% endblock %}

flask_starter/flaskstarter/templates/unconfirmed.html
{% extends "base.html" %}

{% block content %}
<p>You have not confirmed your account. Please check your inbox (and your spam folder) - you should have received an email with a confirmation link.</p>
<!--<p>Didn't get the email? <a href="/">Resend</a>.</p>-->

{% endblock %}